Repository metafy-social/web3-smart-contracts, pull requests merged in 2022-10, with the labels that each got.

#17 Add ERC1155 token contract
  contracts/NFT/erc1155.sol
Labels: good first issue, hacktoberfest, hactoberfest-accepted, feature

#19 Crowd Funding Smart Contract
  contracts/Misc/CrowdFunding.sol
Labels: good first issue, hacktoberfest, hactoberfest-accepted, feature

#23 added faucet contract file
  contracts/Misc/Faucet.sol
Labels: good first issue, hacktoberfest, hactoberfest-accepted, feature

#25 Vesting Contract
  contracts/Misc/Vesting_Contract.sol
Labels: hacktoberfest, hactoberfest-accepted, feature

#28 Gas optimized and currentTime function added
  README.md
  contracts/Misc/CrowdFunding.sol
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#37 Added Voting Contract
  contracts/Coins/erc20std.sol
  contracts/Voting/Election.sol
  contracts/Voting/README.md
Labels: hacktoberfest, hacktoberfest-accepted, feature

#36 Fixes #34
  contracts/Misc/PasswordManager.sol
Labels: hacktoberfest, hacktoberfest-accepted, feature

#40 Added Auction Smart Contract
  contracts/Auction/SimpleAuction.sol
Labels: hacktoberfest, hacktoberfest-accepted, feature

#42 Add Multiple Signature Wallet
  contracts/Misc/MultiSigWallet.sol
Labels: hacktoberfest, hacktoberfest-accepted, feature

#45 ticketing system
  contracts/Misc/TicketingSystem/PriceConverter.sol
  contracts/Misc/TicketingSystem/TicketBooker.sol
Labels: hacktoberfest, hacktoberfest-accepted, feature

#46 added ecommerce contract
  contracts/Ecommerce/ecommerce.sol
Labels: hacktoberfest, hacktoberfest-accepted, feature

#48 Added NFT Drop Registration contract
  contracts/Misc/NFTDropRegistration.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review

#51 Added smart contract for decentralized parking
  contracts/Misc/DecentralizedParking.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#60 Create PersonalDetailStorage
  contracts/Misc/PersonalDetailStorage.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#61 Taxi service smart contract added
  contracts/Misc/TaxiService.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#53 Added coin-flip game smart contract
  contracts/Games/CoinFlip.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#65 MemoApp/issue54
  contracts/Memoapp/GetMemo.sol
  hardhat.config.js
  package.json
  scripts/Memo.js
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#71 ERC-2981 contract (NFT with royalty)
  contracts/NFT/erc2981-erc721.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#62 Restaurant manager smart contract added
  contracts/Misc/RestaurantsManager.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#75 Changes requested for RestaurantsManager contract
  contracts/Misc/RestaurantsManager.sol
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, level-1

#82 Chanlink ETH/USD Price Fetch contract
  contracts/Misc/ChainlinkETHPriceFetch.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#72 health record contract
  contracts/Health-Rec/HealthRec.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#83 Verify merge On chain
  contracts/Misc/ProofOfMerge.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#84 Commit Reveal in solidity
  contracts/Misc/CommitReveal.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#85 Added smart contract to prevent spammers from doing multiple comments
  contracts/PreventSpam/CommentMe.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#86 Reentrancy attack
  contracts/Reentrancy attack/ReentrancyAttack.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#89 Add Messaging Web3 Script
  contracts/Messaging/Messaging.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#87 created supplychain smart contract
  contracts/Supplychain/supplychain.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#92 Escrow Smart Contract
  README.md
  contracts/Escrow/EscrowContract.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#97 added files for FlashLoan contract
  contracts/FlashLoan/FlashLoan.sol
  contracts/FlashLoan/requirements.txt
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#99 Add Casino Game
  contracts/Games/Casino.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#102 Added basic Implementation of Soulbound Token
  README.md
  contracts/NFT/Soulbound.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#104 Add NFT Warranty
  contracts/NFT Warranty/README.md
  contracts/NFT Warranty/nft-warranty.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#106 Added Library Management smart contract
  contracts/Misc/LibraryManagement.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#105 English Auction
  contracts/Auction/EnglishAuction.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#109 Added TimeLock contract + testing erc20 contract
  contracts/TimeLock/TestCoin.sol
  contracts/TimeLock/TimeLock.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#110 Added contract for event organization
  contracts/Event_organize/event.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#112 Create Propertyregistery.sol
  contracts/Misc/Propertyregistery.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#124 Delete Memo.js
  README.md
  scripts/Memo.js
Labels: hacktoberfest, hacktoberfest-accepted, PR:No-Issue

#131 Salary Payment System added
  README.md
  contracts/Salary Payment System/README.md
  contracts/Salary Payment System/SalaryPaymentSystem.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#127 BankingSystem.sol
  contracts/Banking/BankingSystem.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#119 Added vaccine tracker smart contract
  contracts/Misc/VaccineTracker.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#120 Dutch Auction
  contracts/Auction/DutchAuction.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#117 Create SharedWallet.sol
  contracts/Shared Wallet/SharedWallet.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#118 Tic Tac Toe Smart Contract
  contracts/Games/tic-tac-toe.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#137 Add blockchain based DNS smart contract #132
  contracts/blockDNS/Description.md
  contracts/blockDNS/dns.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#139 Added Datafeed of eth/usd via Chainlink gateway
  contracts/Real_TimeData_Feed/Readme.md
  contracts/Real_TimeData_Feed/RealTime_Data_Feed.sol
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#147 Update broken link in README.md
  README.md
Labels: hacktoberfest-accepted

#145 Added blog smart contract
  contracts/Blog/Blog.sol
Labels: hacktoberfest-accepted, level-1

#149 Fix broken link
  README.md
Labels: hacktoberfest-accepted, PR:Ready-to-Review

#151 Added Uno Card Game smart contract
  contracts/Games/UnoCard.sol
Labels: hacktoberfest-accepted, level-1
